### ISSUE TITLE
appveyor builds broken 

### ISSUE THREAD

**Issue by sckott** [ropensci/oai#38]
been so for a while now. b/c won't install Rtools if no `/src` dir, but seems to work fine for some pkgs with no `/src` dir, weird.

**Comment by sckott** [comment]
Seems to have fixed appveyor builds making an empty src dir, @mbojan i don't know if cran folks will complain about this, passes check though - it does print on installation something like  "make: nothing to build ..."

**Comment by mbojan** [comment]
I have never used appveyor, but I look at the log (https://ci.appveyor.com/project/sckott/oai/build/1.0.130) and it seems that the error was due to `xml2` which appveyor wants to install from GitHub instead of CRAN. I'm not sure why because it is on CRAN (https://cran.rstudio.com/web/packages/xml2/index.html). Installing from GitHub requires Rtools as you install from sources instead of windows binaries. So the appveyor is to blame because it should install Rtools whenever it needs a package beyond CRAN.

 Ideas for workarounds:

- Can we somehow force appveyor to install `xml2` from CRAN?
- Perhaps `src` can be `.Rbuildignore`-d so that appveyor sees it when downloading the package and installs Rtools, but it will be dropped from the actual build?

Actually, the package does not have any compiled code. If there is no compiled code in a package windows binary is just the ZIP of the folder where the package was installed. If it passes the check on travis, windows-specifc problems are rather unlikely.

**Comment by mbojan** [comment]
I did not answer the original question :/

My bet is that CRAN maintainers will complain.

**Comment by sckott** [comment]
jim hester sent a PR recently https://github.com/ropensci/oai/commit/bfccd7b760b170d387924beaae6cd86e9e4bce05 and added  https://github.com/ropensci/oai/blob/master/DESCRIPTION#L35 so that `xml2` dev version is installed. 

If we stick with the new `xml2` function added in that PR, as soon as new version of `xml2` is on CRAN, we can remove that `Remotes` line in DESC file, and it will be fixed. 

he said `xml2` should go to CRAN in 2-4 weeks from 27 may

**Comment by mbojan** [comment]
OK. So we push `oai` to CRAN then? I'll try to find time to clean-up a thing or two before then (#23, #24, #36...).

**Comment by sckott** [comment]
yes, soon, once new version of `xml2` is on CRAN

**Comment by sckott** [comment]
seems sorted now, closing
